# Generated by Django 4.2.9 on 2024-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0002_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="668eca03dc4e8c729e936ed1", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="668eca03dc4e8c729e936ed4", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="local_path",
            field=models.FileField(upload_to="uploads/grades/"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="668eca03dc4e8c729e936ed3", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="668eca03dc4e8c729e936ed2", max_length=24),
        ),
    ]
