# Generated by Django 4.2.9 on 2024-07-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0004_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="66940680dc4e8c1d08afff83", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="66940680dc4e8c1d08afff86", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="66940680dc4e8c1d08afff85", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="66940680dc4e8c1d08afff84", max_length=24),
        ),
    ]
