# Generated by Django 4.2.9 on 2024-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0005_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="66941026dc4e8c2cb6d9b9e0", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="66941026dc4e8c2cb6d9b9e3", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="66941026dc4e8c2cb6d9b9e2", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="66941026dc4e8c2cb6d9b9e1", max_length=24),
        ),
    ]
