# Generated by Django 4.2.9 on 2024-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0007_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="66941144dc4e8c2e7039af24", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="66941144dc4e8c2e7039af27", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="66941144dc4e8c2e7039af26", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="66941144dc4e8c2e7039af25", max_length=24),
        ),
    ]
