# Generated by Django 4.2.9 on 2024-07-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0008_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="669411fadc4e8c2f682c5d4e", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="669411fadc4e8c2f682c5d51", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="669411fadc4e8c2f682c5d50", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="669411fadc4e8c2f682c5d4f", max_length=24),
        ),
    ]
