# Generated by Django 4.2.9 on 2024-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0011_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="66941be5dc4e8c4347193e87", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="66941be5dc4e8c4347193e8a", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="66941be5dc4e8c4347193e89", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="66941be5dc4e8c4347193e88", max_length=24),
        ),
    ]
