# Generated by Django 4.2.9 on 2024-07-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0012_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_questions",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_rubric",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="6694e19cdc4e8c811f906949", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="6694e19cdc4e8c811f90694c", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="6694e19cdc4e8c811f90694b", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="6694e19cdc4e8c811f90694a", max_length=24),
        ),
    ]
