# Generated by Django 4.2.9 on 2024-07-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0013_alter_assignment_assignment_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="669505cfdc4e8ca9ea5a50ef", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grade.grade",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="669505cfdc4e8ca9ea5a50f2", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="669505cfdc4e8ca9ea5a50f1", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="669505cfdc4e8ca9ea5a50f0", max_length=24),
        ),
    ]
