# Generated by Django 4.2.9 on 2024-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0014_alter_assignment_uuid_alter_bot_grade_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="description",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bot",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="669507cadc4e8cac14fc41a4", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="669507cadc4e8cac14fc41a7", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="669507cadc4e8cac14fc41a6", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="669507cadc4e8cac14fc41a5", max_length=24),
        ),
    ]
