# Generated by Django 4.2.9 on 2024-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0015_bot_description_bot_name_alter_assignment_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="669512f1dc4e8cba4fa770e1", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="669512f1dc4e8cba4fa770e4", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="669512f1dc4e8cba4fa770e3", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="669512f1dc4e8cba4fa770e2", max_length=24),
        ),
    ]
