# Generated by Django 4.2.9 on 2024-07-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0016_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="669519f9dc4e8cc376dbc391", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grade.student",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="669519f9dc4e8cc376dbc394", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="669519f9dc4e8cc376dbc393", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="669519f9dc4e8cc376dbc392", max_length=24),
        ),
    ]
