# Generated by Django 4.2.9 on 2024-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0017_alter_assignment_uuid_alter_bot_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="669519fedc4e8cc38d9057f5", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="669519fedc4e8cc38d9057f8", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="669519fedc4e8cc38d9057f7", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="669519fedc4e8cc38d9057f6", max_length=24),
        ),
    ]
