# Generated by Django 4.2.9 on 2024-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0018_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="custom_prompt",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="669565ffdc4e8cfd9f9831b4", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="669565ffdc4e8cfd9f9831b7", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="669565ffdc4e8cfd9f9831b6", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="669565ffdc4e8cfd9f9831b5", max_length=24),
        ),
    ]
