# Generated by Django 4.2.9 on 2024-07-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0019_bot_custom_prompt_alter_assignment_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="slug",
            field=models.SlugField(default="xxxxx", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="66956dc6dc4e8c0b1db22ba3", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="66956dc6dc4e8c0b1db22ba6", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="66956dc6dc4e8c0b1db22ba5", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="66956dc6dc4e8c0b1db22ba4", max_length=24),
        ),
    ]
