# Generated by Django 4.2.9 on 2024-07-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0022_botmessage_user_alter_assignment_uuid_alter_bot_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="uuid",
            field=models.CharField(default="6696995edc4e8c15de30592e", max_length=24),
        ),
        migrations.AlterField(
            model_name="bot",
            name="uuid",
            field=models.CharField(default="6696995edc4e8c15de305931", max_length=24),
        ),
        migrations.AlterField(
            model_name="botmessage",
            name="uuid",
            field=models.CharField(default="6696995edc4e8c15de305932", max_length=24),
        ),
        migrations.AlterField(
            model_name="grade",
            name="uuid",
            field=models.CharField(default="6696995edc4e8c15de305930", max_length=24),
        ),
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.CharField(default="6696995edc4e8c15de30592f", max_length=24),
        ),
        migrations.CreateModel(
            name="EvaluationPrompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=10)),
                ("prompt_text", models.TextField()),
                ("course_name", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grade.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Prompt",
                "verbose_name_plural": "Evaluation Prompts",
            },
        ),
    ]
