# Generated by Django 4.2.9 on 2024-07-14 17:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video_id", models.CharField(max_length=20, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish")],
                        default="es",
                        max_length=2,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
            ],
        ),
    ]
