# Generated by Django 4.2.9 on 2024-07-14 18:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0002_remove_youtubevideo_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
