# Generated by Django 4.2.9 on 2024-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0003_youtubevideo_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="transcript",
            field=models.TextField(blank=True),
        ),
    ]
