# Generated by Django 4.2.9 on 2024-07-14 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0004_youtubevideo_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="url",
            field=models.URLField(default="null", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="youtubevideo",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
