# Generated by Django 4.2.9 on 2024-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0007_alter_course_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="uuid",
            field=models.CharField(default="669519fedc4e8cc38d9057f9", max_length=24),
        ),
    ]
