# Generated by Django 4.2.9 on 2024-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0008_alter_course_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="uuid",
            field=models.CharField(default="669565ffdc4e8cfd9f9831b8", max_length=24),
        ),
    ]
