# Generated by Django 4.2.9 on 2024-07-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0009_alter_course_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="uuid",
            field=models.CharField(default="66956dc6dc4e8c0b1db22ba7", max_length=24),
        ),
    ]
