# Generated by Django 4.2.9 on 2024-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0010_alter_course_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="uuid",
            field=models.CharField(default="66956f9fdc4e8c0d8b4860e2", max_length=24),
        ),
    ]
