# Generated by Django 4.2.9 on 2024-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0011_alter_course_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="uuid",
            field=models.CharField(default="66957531dc4e8c17390e5521", max_length=24),
        ),
    ]
