# Generated by Django 4.2.9 on 2024-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0012_alter_course_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="uuid",
            field=models.CharField(default="6696995edc4e8c15de305933", max_length=24),
        ),
    ]
