# Generated by Django 4.2.9 on 2024-07-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grade", "0005_alter_assignment_uuid_alter_bot_uuid_and_more"),
        ("users", "0002_profile_city_profile_country_profile_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grade.language",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                default="student",
                max_length=20,
            ),
        ),
    ]
