# Generated by Django 4.2.9 on 2024-07-14 18:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_language_profile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
