# Generated by Django 4.2.9 on 2024-07-09 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0002_grade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
